# Generated by Django 4.1.7 on 2023-04-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_useraccount_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
