# Generated by Django 4.1.7 on 2023-12-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0012_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saveditem',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
