# Generated by Django 4.2.8 on 2023-12-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_chatmessage'),
        ('api', '0013_alter_saveditem_unique_together'),
    ]

    operations = [
    ]
