# Generated by Django 4.1.7 on 2023-12-27 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_saveditem_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('desired_year_month', models.DateField()),
                ('desired_participants', models.PositiveIntegerField()),
                ('destination_tags', models.ManyToManyField(blank=True, related_name='adventures', to='api.tag')),
                ('itinerary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.itinerary')),
                ('participants', models.ManyToManyField(blank=True, related_name='participating_adventures', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
