# Generated by Django 4.1.7 on 2023-12-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_adventure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='desired_year_month',
            field=models.DateField(null=True),
        ),
    ]
