# Generated by Django 4.1.7 on 2024-01-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20231227_1550'),
        ('api', '0017_adventurejoinrequest'),
    ]

    operations = [
    ]
