# Generated by Django 4.1.7 on 2024-01-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_merge_20240103_0956'),
        ('api', '0018_merge_20240103_2340'),
    ]

    operations = [
    ]
